#!/usr/bin/with-contenv bash
set -a
source /etc/colors.sh

PREFFIX="[cont-init.d] $(s6-basename ${0}):"

if [ -z "$SECRETS_SET" ]; then 
    echo "${PREFFIX}${Red} ERROR - Secrets are not set!"
    exit 1
fi

#fix Mountpoint Syntax
#remove / at the end #todo

#create folders
mkdir -p $MountPoint /root/.config/rclone

# Generate multi-drive conf
read -a rclone_team_drive_ids_arr <<< $rclone_team_drive_ids
count=0
for rclone_team_drive_id in "${rclone_team_drive_ids_arr[@]}"; do
    (envsubst < /rclone_conf/rclone_multi_template) >> /root/.config/rclone/rclone.conf
    multi_names="${multi_names} gdrive_mount_crypt_${count}:/:nc"
    count=$((count+1))
done

# Create the union
## Remove leading space
multi_names="${multi_names#"${multi_names%%[![:space:]]*}"}"
(envsubst < /rclone_conf/rclone_union) >> /root/.config/rclone/rclone.conf