version: 1
update_configs:
  - package_manager: "docker"
    directory: "/bazarr/"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/gdrive-service-accounts/"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/radarr/"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/rclone/"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/sonarr/"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/traktarr/"
    update_schedule: "weekly"
