#!/usr/bin/with-contenv sh

#set -x

source /etc/colors.sh

PREFFIX="[services.d] [rclone-mount]-$(s6-basename ${0}):"

SERVICE_DIR=/var/run/s6/services
SERVICE=rclone-mount

checkRclone(){
    ps aux | grep '.rclon[e].*'$RemotePath'' | grep -v grep > /dev/null
    return $?
}

if checkRclone; then
    s6-svc -d ${SERVICE_DIR}/${SERVICE}
    tempPID="$(pgrep rclon[e])"
    kill ${tempPID}
else
    echo -e "${PREFFIX} ${Red}rclone process not present, restarting container[ERROR]${Color_Off}"
    s6-svscanctl -t /var/run/s6/services
fi

echo -e "${PREFFIX} ${Yellow}waiting for rclone shutdown${Color_Off}"
while checkRclone -eq 0; do
    sleep 0.1
done