#!/usr/bin/with-contenv bash
cd /config/.unmanic/logs && \
rm -f tornado.log* unmanic.log* && \
ln -sf /proc/1/fd/1 tornado.log && \
ln -sf /proc/1/fd/1 unmanic.log && \
chown -h 65534:65534 tornado.log unmanic.log
