#!/usr/bin/with-contenv bash
set +x
set -o pipefail

# This script checks for any timestamps in the future in the upload folder and fixes them
#  so the upload script can run.

_term() { 
  echo "Caught SIGTERM"
  exit 0
}

trap _term SIGTERM

PREFIX=Media/
SOURCE=/shared/separate/$PREFIX

function changeTimestamp() {
  local path=$1
  local fromTimestamp=$(date -r $path)
  echo "[fix-timestamps] Changing $path timestamp of $fromTimestamp to current time"
  touch $1
}
export -f changeTimestamp

cd "$SOURCE"

while true; do
  touch /tmp/now
  find ~+ -newer /tmp/now -exec bash -c 'changeTimestamp "$0"' {} +
  sleep 600
done
