name: Build containers

on: 
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  cancel_redundant:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: 
          - image: "makeshift27015/bazarr"
            dockerfile: "bazarr.Dockerfile"

          - image: "makeshift27015/marauder_gcloud_init"
            dockerfile: "gcloud_init/Dockerfile"

          - image: "makeshift27015/radarr"
            dockerfile: "radarr/Dockerfile"

          - image: "makeshift27015/rclone"
            dockerfile: "rclone/Dockerfile"

          - image: "makeshift27015/marauder_rclone_generate_keys"
            dockerfile: "rclone_generate_keys/Dockerfile"

          - image: "makeshift27015/sonarr"
            dockerfile: "sonarr/Dockerfile"

          - image: "makeshift27015/traktarr"
            dockerfile: "traktarr/Dockerfile"
          
          - image: "makeshift27015/headphones"
            dockerfile: "headphones.Dockerfile"
          
          - image: "makeshift27015/lazylibrarian"
            dockerfile: "lazylibrarian.Dockerfile"
          
          - image: "makeshift27015/medusa"
            dockerfile: "medusa.Dockerfile"
          
          - image: "makeshift27015/mylar"
            dockerfile: "mylar.Dockerfile"
          
          - image: "makeshift27015/nzbhydra2"
            dockerfile: "nzbhydra2.Dockerfile"
          
          - image: "makeshift27015/sabnzbd"
            dockerfile: "sabnzbd.Dockerfile"
          
          - image: "makeshift27015/transmission"
            dockerfile: "transmission.Dockerfile"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build ${{ matrix.group.image }}
        uses: ./.github/actions/build-and-push-container
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: ${{ matrix.group.dockerfile }}
          image: ${{ matrix.group.image }}
