name: Build containers

on:
  push:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  cancel_redundant:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group:
          - image: "makeshift27015/bazarr"
            dockerfile: "bazarr.Dockerfile"
            readme_location: "generic-docker-readme.md"

          - image: "makeshift27015/marauder_gcloud_init"
            dockerfile: "gcloud_init/Dockerfile"
            readme_location: "gcloud_init/Readme.md"

          - image: "makeshift27015/radarr"
            dockerfile: "radarr/Dockerfile"
            readme_location: "radarr/Readme.md"

          - image: "makeshift27015/rclone"
            dockerfile: "rclone/Dockerfile"
            readme_location: "rclone/Readme.md"

          - image: "makeshift27015/marauder_rclone_generate_keys"
            dockerfile: "rclone_generate_keys/Dockerfile"
            readme_location: "rclone_generate_keys/Readme.md"

          - image: "makeshift27015/sonarr"
            dockerfile: "sonarr/Dockerfile"
            readme_location: "sonarr/Readme.md"

          - image: "makeshift27015/traktarr"
            dockerfile: "traktarr/Dockerfile"
            readme_location: "traktarr/Readme.md"

          - image: "makeshift27015/headphones"
            dockerfile: "headphones.Dockerfile"
            readme_location: "generic-docker-readme.md"

          - image: "makeshift27015/lazylibrarian"
            dockerfile: "lazylibrarian.Dockerfile"
            readme_location: "generic-docker-readme.md"

          - image: "makeshift27015/medusa"
            dockerfile: "medusa.Dockerfile"
            readme_location: "generic-docker-readme.md"

          - image: "makeshift27015/mylar"
            dockerfile: "mylar.Dockerfile"
            readme_location: "generic-docker-readme.md"

          - image: "makeshift27015/nzbhydra2"
            dockerfile: "nzbhydra2.Dockerfile"
            readme_location: "generic-docker-readme.md"

          - image: "makeshift27015/sabnzbd"
            dockerfile: "sabnzbd.Dockerfile"
            readme_location: "generic-docker-readme.md"

          - image: "makeshift27015/transmission"
            dockerfile: "transmission.Dockerfile"
            readme_location: "generic-docker-readme.md"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build ${{ matrix.group.image }}
        uses: ./.github/actions/build-and-push-container
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: ${{ matrix.group.dockerfile }}
          image: ${{ matrix.group.image }}
          readme_location: ${{ matrix.group.readme_location }}
