name: Build containers

on: 
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  cancel_redundant:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: 
          - image: "makeshift27015/bazarr"
            context: "bazarr/"
          - image: "makeshift27015/marauder_gcloud_init"
            context: "gcloud_init/"
          - image: "makeshift27015/radarr"
            context: "radarr/"
          - image: "makeshift27015/rclone"
            context: "rclone/"
          - image: "makeshift27015/marauder_rclone_generate_keys"
            context: "rclone_generate_keys/"
          - image: "makeshift27015/sonarr"
            context: "sonarr/"
          - image: "makeshift27015/traktarr"
            context: "traktarr/"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build ${{ matrix.group.image }}
        uses: ./.github/actions/build-and-push-container
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: ${{ matrix.group.context }}
          image: m${{ matrix.group.image }}
