name: Build containers

on: 
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  cancel_redundant:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build bazarr
        uses: ./.github/actions/build-and-push-container
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: bazarr/
          image: makeshift27015/bazarr

      - name: Build gcloud init
        uses: ./.github/actions/build-and-push-container
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: gcloud_init/
          image: makeshift27015/marauder_gcloud_init

      - name: Build radarr
        uses: ./.github/actions/build-and-push-container
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: radarr/
          image: makeshift27015/radarr

      - name: Build rclone
        uses: ./.github/actions/build-and-push-container
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: rclone/
          image: makeshift27015/rclone

      - name: Build rclone generate keys
        uses: ./.github/actions/build-and-push-container
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: rclone_generate_keys/
          image: makeshift27015/marauder_rclone_generate_keys

      - name: Build sonarr
        uses: ./.github/actions/build-and-push-container
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: sonarr/
          image: makeshift27015/sonarr

      - name: Build traktarr
        uses: ./.github/actions/build-and-push-container
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: traktarr/
          image: makeshift27015/traktarr
